### ISSUE TITLE
Add a link to see the current list of challenges

### ISSUE THREAD

**Issue by sameerajayasoma** [Ballroom-Platform/ballroom-frontend#40]
See this screenshot. I can see a way to see the upcoming list of contests, but there is no way to see the current list of challenges.  

<img width="934" alt="Screenshot 2023-04-26 at 2 20 56 PM" src="https://user-images.githubusercontent.com/2637328/234705502-d0c01394-efe4-4d02-b74c-2ea8e474cf24.png">

**Comment by haathim** [comment]
Hi all,
There is already a component called "ChallengesByDifficulty" which lists all the challenges according to their difficulty. That component maybe possible to use here for this issue.
