### ISSUE TITLE
Introduce a mechanism to view the list of all contests, past, present and future.

### ISSUE THREAD

**Issue by sameerajayasoma** [Ballroom-Platform/ballroom-frontend#41]
On the admin page, I should be able to see the upcoming and all contests. 

I should be able to filter out contests based on past and already started or future contests.

**Comment by ManujaDewmina** [comment]
[https://github.com/Ballroom-Platform/ballroom-frontend/commit/065a93fd9b1f8a85736af80af065081c679a311f](url)
